"""`check_precommit_installed.py` 가 **실제로 가르는가** — 작업 2.3 / SC-3·SC-5.

이 저장소의 검사기는 통과만으로 끝나지 않는다(§13.0.1 ④). 이 파일이 그 몫이며,
음성 셋 + 양성 하나를 임시 사본으로 만들어 판정이 갈리는지 본다.

**왜 이 검사기를 만들었는지가 이 파일의 요점이기도 하다.**
`test_ci_gates.py::test_private_data_scan_runs_in_both_pre_commit_and_ci` 는
`.pre-commit-config.yaml` 에 훅이 **선언돼 있는지**를 본다. 그것은 초록불이었고,
그 상태에서 로컬 절대 경로가 담긴 커밋이 아무 저항 없이 만들어졌다 — `.git/hooks/`
가 비어 있었기 때문이다(R25 실측). **선언과 설치 사이를 아무도 보지 않았다.**
"""

from __future__ import annotations

import importlib.util
import subprocess
from pathlib import Path
from types import ModuleType

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / "scripts" / "check_precommit_installed.py"


def _load() -> ModuleType:
    spec = importlib.util.spec_from_file_location("check_precommit_installed", SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _repo(tmp_path: Path, *, config: bool = True, hook: str | None = None) -> Path:
    """작업 사본을 흉내 낸다 — 설정 파일과 훅 파일의 유무·내용만이 판정 입력이다."""
    if config:
        (tmp_path / ".pre-commit-config.yaml").write_text(
            "repos: []\n", encoding="utf-8"
        )
    hooks_dir = tmp_path / ".git" / "hooks"
    hooks_dir.mkdir(parents=True)
    if hook is not None:
        (hooks_dir / "pre-commit").write_text(hook, encoding="utf-8")
    return tmp_path


@pytest.mark.req("SC-5")
def test_missing_hook_is_detected(tmp_path: Path) -> None:
    """음성 ① 설정만 있고 훅이 없다 — **이것이 R25 에 실제로 있던 상태다.**"""
    ok, why = _load().hook_state(_repo(tmp_path))
    assert not ok
    assert "pre-commit" in why


@pytest.mark.req("SC-5")
def test_a_foreign_hook_does_not_count_as_installed(tmp_path: Path) -> None:
    """★ 음성 ② 훅 파일이 **있기만** 하면 통과시키면 안 된다.

    다른 도구가 놓은 훅이나 손으로 만든 빈 파일도 「설치됨」이 되어, 검사가
    무엇도 붙들지 않으면서 초록불을 낸다 — 이 저장소가 반복해 만난 형태다.
    """
    ok, why = _load().hook_state(_repo(tmp_path, hook="#!/bin/sh\nexit 0\n"))
    assert not ok
    assert "프레임워크" in why


@pytest.mark.req("SC-5")
def test_missing_config_is_detected(tmp_path: Path) -> None:
    """음성 ③ 설정 자체가 사라진 경우 — 훅이 걸려 있어도 돌 규칙이 없다."""
    ok, _ = _load().hook_state(
        _repo(tmp_path, config=False, hook="# pre-commit generated\n")
    )
    assert not ok


@pytest.mark.req("SC-5")
def test_a_real_precommit_hook_passes(tmp_path: Path) -> None:
    """양성 — 정상 상태를 통과시킨다.

    음성만 두면 「무엇이든 거부하는」 구현도 전건 통과하므로 함께 본다.
    """
    ok, why = _load().hook_state(
        _repo(tmp_path, hook="#!/bin/sh\n# File generated by pre-commit\n")
    )
    assert ok, why


@pytest.mark.req("SC-5")
def test_the_hook_is_found_from_inside_a_worktree(tmp_path: Path) -> None:
    """★ **worktree 에서는 `.git` 이 파일이다** — 경로를 하드코딩하면 거짓 빨간불.

    R38 실측: `repo_root / ".git" / "hooks" / "pre-commit"` 로 굳어 있어서 worktree
    안에서 이 검사가 **「설치되지 않음」** 이라 말했다. 그런데 git 은 worktree 에서도
    **공통 hooks 디렉터리**를 쓰므로 훅은 실제로 걸린다 — 위반이 없는데 위반이라고
    보고하는 «시끄러운» 실패다(`status.md` 함정 절).

    ⚠ **본 저장소만 보는 검사로는 이 결함을 볼 수 없다** — 거기서는 하드코딩한 경로와
    git 이 답하는 경로가 **같은 곳**이다. 그래서 이 검사는 임시 worktree 를 실제로
    만든다. 그 자리가 비어 있었던 것이 결함이 살아 있던 이유다.

    본 저장소에 훅이 설치돼 있지 않은 기계(CI 등)에서는 잴 것이 없으므로 건너뛴다 —
    이 검사가 재는 것은 「훅이 있는가」가 아니라 **「같은 훅을 worktree 에서도 찾는가」**다.
    """
    module = _load()
    if not module.hook_state(REPO_ROOT)[0]:
        pytest.skip("본 저장소에 pre-commit 훅이 설치돼 있지 않다 — 대조할 양성이 없다")

    work = tmp_path / "wt"
    add = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "worktree", "add", "--detach", str(work)],
        capture_output=True,
        text=True,
        check=False,
    )
    if add.returncode != 0:  # git 이 없거나 worktree 를 만들 수 없는 환경
        pytest.skip(f"worktree 를 만들 수 없다: {add.stderr.strip()}")
    try:
        assert (work / ".git").is_file(), (
            "worktree 의 `.git` 이 파일이 아니다 — 이 검사의 전제가 깨졌다"
        )
        ok, why = module.hook_state(work)
        assert ok, (
            f"worktree 에서 훅을 찾지 못했다: {why} — 훅 디렉터리를 "
            "`git rev-parse --git-path hooks` 에 물어야 한다"
        )
    finally:
        subprocess.run(
            ["git", "-C", str(REPO_ROOT), "worktree", "remove", "--force", str(work)],
            capture_output=True,
            text=True,
            check=False,
        )
