"""`check_precommit_installed.py` 가 **실제로 가르는가** — 작업 2.3 / SC-3·SC-5.

이 저장소의 검사기는 통과만으로 끝나지 않는다(§13.0.1 ④). 이 파일이 그 몫이며,
음성 셋 + 양성 하나를 임시 사본으로 만들어 판정이 갈리는지 본다.

**왜 이 검사기를 만들었는지가 이 파일의 요점이기도 하다.**
`test_ci_gates.py::test_private_data_scan_runs_in_both_pre_commit_and_ci` 는
`.pre-commit-config.yaml` 에 훅이 **선언돼 있는지**를 본다. 그것은 초록불이었고,
그 상태에서 로컬 절대 경로가 담긴 커밋이 아무 저항 없이 만들어졌다 — `.git/hooks/`
가 비어 있었기 때문이다(R25 실측). **선언과 설치 사이를 아무도 보지 않았다.**
"""

from __future__ import annotations

import importlib.util
from pathlib import Path
from types import ModuleType

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / "scripts" / "check_precommit_installed.py"


def _load() -> ModuleType:
    spec = importlib.util.spec_from_file_location("check_precommit_installed", SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _repo(tmp_path: Path, *, config: bool = True, hook: str | None = None) -> Path:
    """작업 사본을 흉내 낸다 — 설정 파일과 훅 파일의 유무·내용만이 판정 입력이다."""
    if config:
        (tmp_path / ".pre-commit-config.yaml").write_text(
            "repos: []\n", encoding="utf-8"
        )
    hooks_dir = tmp_path / ".git" / "hooks"
    hooks_dir.mkdir(parents=True)
    if hook is not None:
        (hooks_dir / "pre-commit").write_text(hook, encoding="utf-8")
    return tmp_path


@pytest.mark.req("SC-5")
def test_missing_hook_is_detected(tmp_path: Path) -> None:
    """음성 ① 설정만 있고 훅이 없다 — **이것이 R25 에 실제로 있던 상태다.**"""
    ok, why = _load().hook_state(_repo(tmp_path))
    assert not ok
    assert "pre-commit" in why


@pytest.mark.req("SC-5")
def test_a_foreign_hook_does_not_count_as_installed(tmp_path: Path) -> None:
    """★ 음성 ② 훅 파일이 **있기만** 하면 통과시키면 안 된다.

    다른 도구가 놓은 훅이나 손으로 만든 빈 파일도 「설치됨」이 되어, 검사가
    무엇도 붙들지 않으면서 초록불을 낸다 — 이 저장소가 반복해 만난 형태다.
    """
    ok, why = _load().hook_state(_repo(tmp_path, hook="#!/bin/sh\nexit 0\n"))
    assert not ok
    assert "프레임워크" in why


@pytest.mark.req("SC-5")
def test_missing_config_is_detected(tmp_path: Path) -> None:
    """음성 ③ 설정 자체가 사라진 경우 — 훅이 걸려 있어도 돌 규칙이 없다."""
    ok, _ = _load().hook_state(
        _repo(tmp_path, config=False, hook="# pre-commit generated\n")
    )
    assert not ok


@pytest.mark.req("SC-5")
def test_a_real_precommit_hook_passes(tmp_path: Path) -> None:
    """양성 — 정상 상태를 통과시킨다.

    음성만 두면 「무엇이든 거부하는」 구현도 전건 통과하므로 함께 본다.
    """
    ok, why = _load().hook_state(
        _repo(tmp_path, hook="#!/bin/sh\n# File generated by pre-commit\n")
    )
    assert ok, why
